version: '3.8'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  ingestion:
    build:
      context: ./data_ingestion
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    command: [ "python", "main.py" ]

  processing:
    build:
      context: ./data_processing
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    command: [ "python", "main.py" ]

  genai:
    build:
      context: ./genai_module
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    command: [ "python", "main.py" ]

  dashboard:
    build:
      context: ./analytics_dashboard
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
