version: '3.8'

services:
  db:
    build:
      context: ./database
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  dashboard:
    build:
      context: ./analytics_dashboard
    env_file:
      - .env
    ports:
      - "80:3000"
    depends_on:
      - db

volumes:
  db_data:
