import { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  loader: {
    display: "flex",
    height: "100vh",
    alignItems: "center",
    justifyContent: "center",
    background: "#0a0a0a",
    color: "#888",
    fontFamily: "Poppins, sans-serif",
  },
  page: {
    background: "#0a0a0a",
    color: "#e5e5e5",
    fontFamily: "Poppins, sans-serif",
    minHeight: "100vh",
    padding: "32px 16px",
  },
  wrapper: { maxWidth: 900, margin: "0 auto" },
  header: { textAlign: "center", marginBottom: 32 },
  title: { fontSize: "2.5rem", fontWeight: 700, margin: 0 },
  subtitle: { marginTop: 8, color: "#888" },
  section: { marginBottom: 48 },
  sectionTitle: { fontSize: "1.25rem", fontWeight: 600, marginBottom: 16 },
  sectionBox: {
    border: "1px solid #444",
    borderRadius: 8,
    padding: 16,
    display: "flex",
    flexWrap: "wrap",
    gap: 16,
  },
  card: {
    background: "#1f1f1f",
    borderRadius: 8,
    flex: "1 1 200px",
    padding: 16,
    boxShadow: "0 2px 4px rgba(0,0,0,0.5)",
    display: "flex",
    flexDirection: "column",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  incId: { fontSize: "1rem", fontWeight: 600 },
  status: {
    fontSize: "0.75rem",
    fontWeight: 500,
    padding: "2px 6px",
    borderRadius: 9999,
  },
  desc: { fontSize: "0.875rem", color: "#bbb", marginBottom: 8 },
  recBox: {
    marginTop: "auto",
    padding: 12,
    background: "#0a0a0a",
    border: "1px solid #444",
    borderRadius: 6,
  },
  noRec: {
    fontSize: "0.875rem",
    fontStyle: "italic",
    color: "#888",
    marginTop: "auto",
  },
  label: {
    fontSize: "0.75rem",
    fontWeight: 500,
    color: "#888",
    textTransform: "uppercase",
    marginBottom: 8,
  },
  value: { fontSize: "1.5rem", fontWeight: 700, color: "#2563eb" },
  date: { marginTop: 4, fontSize: "0.75rem", color: "#888" },
  suggestion: { marginTop: 8 },
  suggestionText: {
    margin: 0,
    color: "#e5e5e5",
    fontSize: "0.875rem",
    whiteSpace: "pre-wrap",
  },
  suggestionButton: {
    marginTop: 4,
    background: "none",
    border: "none",
    color: "#2563eb",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontFamily: "Poppins, sans-serif",
  },
};
